---
- hosts: all
  tasks:
  - name: Start the configured deployment service
    systemd:
      name: "{{ nixos_deploy_service }}"
      state: restarted
      scope: system
    become: yes
    async: 3600
    poll: 10

