# yaml-language-server: $schema=https://raw.githubusercontent.com/ansible/schemas/main/f/ansible.json
---
- hosts: all
  ignore_unreachable: true
  tasks:
  - name: Start the configured deployment service
    command: "sudo systemctl --system start {{ nixos_deploy_service }}"
    become: no
    async: 3600
    poll: 10
